/groups/:groupName 404 improvements;
nextstrain/nextstrain.org pull request #336
Opened 2021-05-21 23:51 UTC by eharkins

For /groups/:groupName/*

If groupName doesn't exist, we show a message with a link to /groups.

If groupName does exist but * isn't a dataset in that group,
we show /groups/:groupName with a message saying * doesn't exist.

2021-05-24 07:05 UTC, jameshadfield requested changes

2021-05-24 07:05 UTC, jameshadfield commented on static-site/src/sections/individual-group-page.jsx
> +        missingDataset: this.props["*"]
Currently this `setState` call happens c. 1000ms (on my machine) after the page actually loads, however the prop is available immediately. (Note that the prop can be assigned to state within the constructor if you wish to rename it, which I agree is sensible.) 

Given that the load time is already affected by the dataset existence check (server-side), we should try to render a useful UI as soon as possible. If we know a dataset is missing, we could display a "something's gone wrong, fetching more information" banner straight away. Furthermore, if we were to enforce all banners to be the same height, then we could simply update this banner with a more informative message as more data arrives. 

There are plenty of options of how exactly to do this, and the first priority should be clarity, with responsiveness (speed) second.

2021-05-26 19:54 UTC, eharkins commented on static-site/src/components/splash/errorMessages.jsx
> +export const MissingGroupsDatasetBanner = ({dataset, groupName}) => (
See #339

2021-05-26 20:16 UTC, eharkins commented
Not sure why but a smoke test (https://travis-ci.com/github/nextstrain/nextstrain.org/builds/226854996#L831) failed the first time around so I force pushed and it passed.

2021-05-28 08:09 UTC, jameshadfield commented
Thanks @eharkins -- I'm going to merge this as-is as it's working well!

One improvement: when attempting to load a non-existent dataset from a non-existent group we get two error messages, whereas we should only get one. This logic can be cleaned up in a future PR, perhaps in #339

![image](https://user-images.githubusercontent.com/8350992/119951772-71f6fb80-bff0-11eb-803e-d8f3b7bb7433.png)

2021-05-28 08:09 UTC, merged