add banner prop to generic page component;
nextstrain/nextstrain.org pull request #339
Opened 2021-05-25 21:14 UTC by eharkins

Allows adding a full-page-width banner to the top
of the page via the prop `bannerContents`.

### Description of proposed changes    
What is the goal of this pull request? What does this pull request change?

### Related issue(s)  

Fixes #  
Related to #  

### Testing
What steps should be taken to test the changes you've proposed?  
If you added or changed behavior in the codebase, did you update the tests, or do you need help with this?

2021-05-26 19:53 UTC, eharkins commented
Just noting https://www.nytimes.com/404 as a good example of this type of UI pointed out by James.

2021-05-28 08:22 UTC, jameshadfield requested changes
There are a few inconsistencies in the component design here, where some error messages use the new UI, and some don't (see https://nextstrain-s-generic-pa-o1n5ib.herokuapp.com/groups/not-a-group for an example of the latter). I'd suggest exposing a component along the lines of `<ErrorBanner>` which can be reused all across the static content, rather than individual components such as `GroupsDatasetNotFound`. This generic error banner could take (e.g.) a title & content prop to facilitate consistency. 

Other UI suggestions:

* If this component were to have a fixed height, we could update the props supplied without causing UI flickering. (For instance, when loading /groups/not-a-group/not-a-dataset, we can immediately display an error banner indicating the dataset doesn't exist, but it takes some time before we can update the banner indicating that the group doesn't exist either!)
* The banner should have more vertical padding above it, across all screen sizes I tested
* I don't think grey is the right colour for the background, but I don't have the perfect colour to suggest at the moment!

2021-06-04 21:01 UTC, eharkins commented
Thanks @jameshadfield for the review! I exposed `ErrorBanner` at your suggestion and tweaked the padding a bit and set the height. Regarding the color, I couldn't come up with anything better looking in my opinion than grey. Maybe we don't need to set the background color? Or were you hoping it would be even more contrasting / louder than the grey I chose?

2021-06-28 04:56 UTC, jameshadfield commented
@eharkins I'm going to merge this into `next` as-is, ao that when `next` is deployed to the live site the UI for individual groups pages can take advantage of the work here. I'll create a separate issue to discuss the next steps for the error UI started in this PR.

2021-06-28 04:56 UTC, merged